CREATE TABLE ZSYSWWF.T_HIST_ANNNAIHAKKOU
(
    SEQ_NO CHAR(12) NOT NULL,
    REC_NO CHAR(2) NOT NULL,
    TREATER_NM NVARCHAR(60),
    CHARGE_NM NVARCHAR(60),
    ACCOUNT_FLG CHAR(1),
    ACCOUNT_OTRS NVARCHAR(100),
    SCENARIO_Y NVARCHAR(4),
    SCENARIO_M NVARCHAR(2),
    REISSUE_REASON_FLG CHAR(1),
    REISSUE_REASON_OTRS NVARCHAR(800),
    CONTRACTOR_NM NVARCHAR(60),
    STOCK_CNT NVARCHAR(5),
    STOCK_NO NVARCHAR(10),
    STOCK_FREE_SPACE NVARCHAR(1200),
    RECEIVER_FLG CHAR(1),
    RECEIVER_POST1 NVARCHAR(3),
    RECEIVER_POST2 NVARCHAR(4),
    RECEIVER_ADDRESS NVARCHAR(200),
    OTHERS NVARCHAR(800),
    RECEIPT_MESSAGE NVARCHAR(800),
    CREATED_BY NVARCHAR(10),
    CREATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(10),
    UPDATED_DATE DATETIME
);
ALTER TABLE ZSYSWWF.T_HIST_ANNNAIHAKKOU ADD CONSTRAINT PK_T_HIST_ANNNAIHAKKOU
    PRIMARY KEY (SEQ_NO, REC_NO);